set (CMAKE_SYSTEM_NAME Linux)
set (CMAKE_SYSTEM_PROCESSOR armv8l)

set (CMAKE_SYSROOT "/usr/local/armv8l-unknown-linux-gnueabihf/armv8l-unknown-linux-gnueabihf/sysroot")
set (ARM_LINUX_SYSROOT "/usr/local/armv8l-unknown-linux-gnueabihf/armv8l-unknown-linux-gnueabihf/sysroot")
set (CMAKE_C_COMPILER "/usr/local/armv8l-unknown-linux-gnueabihf/bin/armv8l-unknown-linux-gnueabihf-gcc")
set (CMAKE_CXX_COMPILER "/usr/local/armv8l-unknown-linux-gnueabihf/bin/armv8l-unknown-linux-gnueabihf-g++")
set (CMAKE_LINKER "/usr/local/armv8l-unknown-linux-gnueabihf/bin/armv8l-unknown-linux-gnueabihf-ld" CACHE FILEPATH "Linker")
set (CMAKE_AR "/usr/local/armv8l-unknown-linux-gnueabihf/bin/armv8l-unknown-linux-gnueabihf-ar" CACHE FILEPATH "Archiver")
set (PKG_CONFIG_EXECUTABLE "/usr/local/bin/pkg-config")
set (ENV{PKG_CONFIG_DIR} "")
set (ENV{PKG_CONFIG_LIBDIR} "/usr/local/armv8l-unknown-linux-gnueabihf/qt5-rpi/lib/pkgconfig")
set (ENV{PKG_CONFIG_SYSROOT_DIR} ${CMAKE_SYSROOT})

set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mcpu=cortex-a53 -mfloat-abi=hard -mfpu=neon-fp-armv8")
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mcpu=cortex-a53 -mfloat-abi=hard -mfpu=neon-fp-armv8")
set (CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -mtune=cortex-a53 -O3")
set (CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -mtune=cortex-a53 -O3")
set (CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} -mtune=cortex-a53 -O3")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} -mtune=cortex-a53 -O3")
